extern crate hello_lib;
extern crate rustcpp_lib;
extern crate num_cpus;

use hello_lib::greeter;
use rustcpp_lib::infoprinter;

fn main() {
    let hello = greeter::Greeter::new("\nHello");
    hello.greet("from Rust!\n");

    let printer: &str = &infoprinter::InfoPrinter::new();
    println!("{}\n", printer);

    let num = num_cpus::get();
    println!("The logical number of cores on this computer, generated by cargo-raze: {}\n", num)
}
